### PR TITLE
Fix for #694

### PR DESCRIPTION
**Pull request by Fernando-Martinez**
Renamed .db files so they match the table names the scrapper is looking for

### CODE REVIEW

**Comment by DIGITALCRIMINAL** [comment]
It's not the fix

**Comment by Fernando-Martinez** [comment]
okay, well if its not the right fix, its at least working as a temporary workaround ¯\_(ツ)_/¯

**Comment by DIGITALCRIMINAL** [comment]
Could you please send me the test db please? They contain no data.
You can view here
http://inloop.github.io/sqlite-viewer/

**Comment by DIGITALCRIMINAL** [comment]
Reason why it's not the fix is because test_metadata never gets called anyhere in the script.

**Comment by Fernando-Martinez** [comment]
okay, i confirm the test dbs are empty. But i renamed those dbs back to "test_" and getting failures again.

heres the full stack trace.

Traceback (most recent call last):
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: posts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\repos\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\repos\OnlyFans\datascraper\main_datascraper.py", line 87, in start_datascraper
    x = main_helper.process_names(
  File "D:\repos\OnlyFans\helpers\main_helper.py", line 570, in process_names
    result = module.start_datascraper(
  File "D:\repos\OnlyFans\modules\onlyfans.py", line 147, in start_datascraper
    results = prepare_scraper(
  File "D:\repos\OnlyFans\modules\onlyfans.py", line 683, in prepare_scraper
    w = process_metadata(metadata_path, new_metadata,
  File "D:\repos\OnlyFans\modules\onlyfans.py", line 555, in process_metadata
    Session, api_type, folder = main_helper.make_metadata(
  File "D:\repos\OnlyFans\helpers\main_helper.py", line 214, in make_metadata
    x = legacy_database_fixer(database_path, database, database_name)
  File "D:\repos\OnlyFans\helpers\main_helper.py", line 167, in legacy_database_fixer
    post_db = result.all()
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py", line 3373, in all
    return list(self)
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: posts
[SQL: SELECT posts.id AS posts_id, posts.text AS posts_text, posts.price AS posts_price, posts.paid AS posts_paid, posts.created_at AS posts_created_at
FROM posts]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by Fernando-Martinez** [comment]
This failure only happens when using metadata from site that was already scrapped before the update. Once i drop the "test_", the scrappe works, the metadata gets updated, and then it cant get repro anymore.

**Comment by Fernando-Martinez** [comment]
I believe its here in the main_helper.py

image

**Comment by DIGITALCRIMINAL** [comment]
kk, could you send me one of the test databases that is broken so I can compare with mine

**Comment by Fernando-Martinez** [comment]
this is the Messages.db that got created in the site metadata folder which has no tables:

[Messages.zip](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5791833/Messages.zip)

Only only gets created incorrectly like that when .db file under /database/databases/ have "test_"

**Comment by Fernando-Martinez** [comment]
Went ahead and removed the "test_" from test_messages.db and scrapped the site agian, and now the Messages.db got created successfully. Here:

[Messages.zip](https://github.com/DIGITALCRIMINAL/OnlyFans/files/5791837/Messages.zip)

**Comment by Fernando-Martinez** [comment]
theres obviously something in main_helper.py->legacy_database_fixer using it as reference or something

**Comment by DIGITALCRIMINAL** [comment]
It's most likely something to do with pre alembic databases then, I'd need to test that since test_messages.db never gets called anywhere.

**Pull request closed without merging**
