### PR TITLE
Linux support and OnlyFans improvements

### PR DESCRIPTION
**Pull request by aboredpervert**
Add some better support for Linux platform.
Optimize OnlyFans download speed and add media ID filename format parameter.

### CODE REVIEW

**Comment by DIGITALCRIMINAL** [comment]
I can't approve
Don't fetch file size.
It's would break the custom script that I've built.

**Comment by aboredpervert** [comment]
What if I put it behind a setting (that defaults to checking it)?

**Comment by DIGITALCRIMINAL** [comment]
> What if I put it behind a setting (that defaults to checking it)?

There's already a setting for that; it's called overwrite files, but I need to put the json_request into the if statement

**Comment by aboredpervert** [comment]
Okay, thanks for merging.
I still think the request can be avoided if we can be sure there are no partial files left (by deleting them on failure).
I will work on another PR and try to reuse the overwrite files setting instead of introducing a new one.

**Comment by DIGITALCRIMINAL** [comment]
> Okay, thanks for merging.
> I still think the request can be avoided if we can be sure there are no partial files left (by deleting them on failure).
> I will work on another PR and try to reuse the overwrite files setting instead of introducing a new one.

It's only a head request. The request doesn't do anything intensive. I've been through a lot of ways to detect if an image is partially downloaded, and sending a head request to get the file size then doing a comparison is the fastest way to check thousands of files with no false positives.

**Comment by aboredpervert** [comment]
> It's only a head request. The request doesn't do anything intensive. I've been through a lot of ways to detect if an image is partially downloaded, and sending a head request to get the file size then doing a comparison is the fastest way to check thousands of files with no false positives.

You are right, it is the fastest way. Assuming you want to check them.

When I do a daily "scrape everything new", I don't want it to make 20000 head requests just to get 10 more files. First because of the time it takes, second because of possibility of detection/rate-limiting, etc.

And partial files are only a problem if they are not cleaned up on failure. On my fork right now I have a new commit that adds cleanup (https://github.com/aboredpervert/OnlyFans/commit/3d93abd0abd252947af91019592a69e4a159481d) so it's guaranteed that no partial files remain.

**Comment by DIGITALCRIMINAL** [comment]
> > It's only a head request. The request doesn't do anything intensive. I've been through a lot of ways to detect if an image is partially downloaded, and sending a head request to get the file size then doing a comparison is the fastest way to check thousands of files with no false positives.
> 
> You are right, it is the fastest way. Assuming you want to check them.
> 
> When I do a daily "scrape everything new", I don't want it to make 20000 head requests just to get 10 more files. First because of the time it takes, second because of possibility of detection/rate-limiting, etc.
> 
> And partial files are only a problem if they are not cleaned up on failure. On my fork right now I have a new commit that adds cleanup ([aboredpervert@3d93abd](https://github.com/aboredpervert/OnlyFans/commit/3d93abd0abd252947af91019592a69e4a159481d)) so it's guaranteed that no partial files remain.

Alright thanks, it looks good. You can add PR. I'll probably remove the request after I edit some stuff.

**Pull request closed without merging**
