### PR TITLE
Get the full blacklist when there's more than 100 user inside it

### LINKED ISSUE #661: Blacklist is limited to 100 users
If there's more than 100 users in the blacklist, only the first 100 will be filtered out.

As a workaround locally I made it so that the offset sent to `api.get_list_users` is incremented by `100` while `offset < bannedCount` to retrieve them all. Though I don't know if this limit on 100 users on the blacklist was on purpose or if it's a real issue.

### PR DESCRIPTION
**Pull request by RakSrinaNa**
I don't know if you'd have it done that way but as #661 is probably low priority for you I share you what I did on my side as a temp fix.

Fixes #661

### CODE REVIEW

**Comment by DIGITALCRIMINAL** [comment]
The change has to be in the actual API https://github.com/DIGITALCRIMINAL/OnlyFans/blob/a957646ffa36211c1f677af0d1848cddb446f15a/apis/onlyfans/onlyfans.py#L704

**Comment by RakSrinaNa** [comment]
On the same way it's done here?

https://github.com/DIGITALCRIMINAL/OnlyFans/blob/a957646ffa36211c1f677af0d1848cddb446f15a/apis/onlyfans/onlyfans.py#L737-L740

**Comment by DIGITALCRIMINAL** [comment]
> On the same way it's done here?
> 
> https://github.com/DIGITALCRIMINAL/OnlyFans/blob/a957646ffa36211c1f677af0d1848cddb446f15a/apis/onlyfans/onlyfans.py#L737-L740

Yeee like that if OF does return a hasMore

**Comment by DIGITALCRIMINAL** [comment]
> On the same way it's done here?
> 
> https://github.com/DIGITALCRIMINAL/OnlyFans/blob/a957646ffa36211c1f677af0d1848cddb446f15a/apis/onlyfans/onlyfans.py#L737-L740

Yeee like that if OF does return a hasMore on this line

https://github.com/DIGITALCRIMINAL/OnlyFans/blob/a957646ffa36211c1f677af0d1848cddb446f15a/apis/onlyfans/onlyfans.py#L700

**Comment by DIGITALCRIMINAL** [comment]
> On the same way it's done here?
> 
> https://github.com/DIGITALCRIMINAL/OnlyFans/blob/a957646ffa36211c1f677af0d1848cddb446f15a/apis/onlyfans/onlyfans.py#L737-L740

Also to make the testing faster, you can hard code the limit to 2 since it usually decreases the API request time.
Can change it back to "limit" when it's done 👍

**Comment by RakSrinaNa** [comment]
It doesn't return a `hasMore` field, just a plain list. So I followed the logic here:

https://github.com/DIGITALCRIMINAL/OnlyFans/blob/a957646ffa36211c1f677af0d1848cddb446f15a/apis/onlyfans/onlyfans.py#L797-L799

Not sure what the `check` parameter is for so I kept it the same way.

From what I can personally test seems like it returns the correct amount of people from the list.

**Comment by DIGITALCRIMINAL** [comment]
> It doesn't return a `hasMore` field, just a plain list. So I followed the logic here:
> 
> https://github.com/DIGITALCRIMINAL/OnlyFans/blob/a957646ffa36211c1f677af0d1848cddb446f15a/apis/onlyfans/onlyfans.py#L797-L799
> 
> Not sure what the `check` parameter is for so I kept it the same way.
> 
> From what I can personally test seems like it returns the correct amount of people from the list.

Oh, if the check parameter is set to True, it will only do one iteration.

Thanks, going to merge 👍

**Pull request merged**
